-- ============================================================
--  تحديث جدول التعليقات وإضافة جدول الردود
--  الصق هذا الكود في: Supabase → SQL Editor → New query → Run
-- ============================================================

-- 1) إنشاء جدول الردود -----------------------------------------------------
create table if not exists public.replies (
  id          bigint generated by default as identity primary key,
  comment_id  bigint not null references public.comments(id) on delete cascade,
  name        text not null,
  reply_text  text not null,
  created_at  timestamptz not null default now()
);

-- فهرس لتسريع جلب الردود حسب التعليق
create index if not exists replies_comment_id_idx on public.replies (comment_id);

-- 2) تفعيل RLS على جدول الردود --------------------------------------------
alter table public.replies enable row level security;

-- السماح للجميع بقراءة الردود
drop policy if exists "read_replies_public" on public.replies;
create policy "read_replies_public"
  on public.replies for select
  to anon, authenticated
  using (true);

-- السماح للجميع بإضافة الردود
drop policy if exists "insert_replies_public" on public.replies;
create policy "insert_replies_public"
  on public.replies for insert
  to anon, authenticated
  with check (true);

-- السماح للجميع بحذف الردود (للمسؤول)
drop policy if exists "delete_replies_public" on public.replies;
create policy "delete_replies_public"
  on public.replies for delete
  to anon, authenticated
  using (true);

-- 3) السماح بحذف التعليقات (للمسؤول فقط) -----------------------------------
drop policy if exists "delete_comments_public" on public.comments;
create policy "delete_comments_public"
  on public.comments for delete
  to anon, authenticated
  using (true);

-- ============================================================
--  انتهى ✅  — الآن يوجد:
--  • جدول comments للتعليقات
--  • جدول replies للردود
--  • سياسات RLS للقراءة والإضافة والحذف
-- ============================================================
