-- ============================================================
--  إعداد جدول التعليقات لمنصة SAC · SVT prof
--  الصق هذا الكود في: Supabase → SQL Editor → New query → Run
-- ============================================================

-- 1) جدول التعليقات ---------------------------------------------------------
create table if not exists public.comments (
  id          bigint generated by default as identity primary key,
  name        text not null,          -- اسم المستخدم
  comment     text not null,          -- نص التعليق
  created_at  timestamptz not null default now()
);

-- فهرس لتسريع الترتيب حسب الأحدث
create index if not exists comments_created_at_idx on public.comments (created_at desc);

-- 2) تفعيل الحماية على مستوى الصفوف (RLS) ---------------------------------
alter table public.comments enable row level security;

-- السماح للجميع بقراءة التعليقات
drop policy if exists "read_comments_public" on public.comments;
create policy "read_comments_public"
  on public.comments for select
  to anon, authenticated
  using (true);

-- السماح للجميع بإضافة التعليقات
drop policy if exists "insert_comments_public" on public.comments;
create policy "insert_comments_public"
  on public.comments for insert
  to anon, authenticated
  with check (true);

-- ============================================================
--  انتهى ✅
-- ============================================================
