-- ✅ تسجيل عروض الباوربوينت (135 عرض) في قاعدة البيانات
-- روابط Google Drive مباشرة — الصق في Supabase SQL Editor واضغط Run

insert into public.files (title, category, level, description, url, path) values
  ('بسمة الربيع النظام البيئي', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1oVsI4z0SV_GndS3xnqJhpu6rip0XPjh3/view', 'drive:1oVsI4z0SV_GndS3xnqJhpu6rip0XPjh3'),
  ('تنوع الكائنات الحية', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1_FzQdM5wvCJ17ud2NxGgs0CinXrko1zt/view', 'drive:1_FzQdM5wvCJ17ud2NxGgs0CinXrko1zt'),
  ('حسين مدونة تكيف النباتات مع اوساطها 2', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1C9ksCHrOhfySzgB0OHxXzTGAeV1NcIBK/view', 'drive:1C9ksCHrOhfySzgB0OHxXzTGAeV1NcIBK'),
  ('تنفس الحيوانات واحتلال الاوساط', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1U1MaOuEGcSMUccwdGWecryrLrHQQpD1H/view', 'drive:1U1MaOuEGcSMUccwdGWecryrLrHQQpD1H'),
  ('تنفس الحيوانات بلفنطاسي واحتلال الاوساط2', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1BQmqN0g-x63xCFdsOi9CMoKMKvMK1qAx/view', 'drive:1BQmqN0g-x63xCFdsOi9CMoKMKvMK1qAx'),
  ('م14 تنوع أنماط التنفس عند الحيوان', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/13lZ32kyEtxdw0hN5cRc3e-sPVLjUmwwG/view', 'drive:13lZ32kyEtxdw0hN5cRc3e-sPVLjUmwwG'),
  ('م02 العلاقات بين الكائنات الحية', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1aw3Uj_-2gG4kpjP0rnpoOJJXCDRoCRFw/view', 'drive:1aw3Uj_-2gG4kpjP0rnpoOJJXCDRoCRFw'),
  ('خصائص الوسط الحي', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1jlutO71iuRLSOmMeuqQ-4naAuMcetFma/view', 'drive:1jlutO71iuRLSOmMeuqQ-4naAuMcetFma'),
  ('الوسط الحي', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1cG2N5SWBZ6Xv5k3UYPpwrXhy87-4cuPt/view', 'drive:1cG2N5SWBZ6Xv5k3UYPpwrXhy87-4cuPt'),
  ('مستحاثات', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1uVlUkD_1DBmxUiGi9v_z5KUwFs9mwUj6/view', 'drive:1uVlUkD_1DBmxUiGi9v_z5KUwFs9mwUj6'),
  ('تكيف النباتات في أوساطها', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1mECl49HGdDob0MN2BPZkASh_wmA8hH0e/view', 'drive:1mECl49HGdDob0MN2BPZkASh_wmA8hH0e'),
  ('تحورات المجموع الجذري والخضري', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1xW8Zhoa3NkB1bRW2fy2P44i5fpwu_I5X/view', 'drive:1xW8Zhoa3NkB1bRW2fy2P44i5fpwu_I5X'),
  ('م13 علاقة الجهاز بالوسط عند النبات', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1wT6sgcirZD8va3ZXAiTQrE5uKqwNsEfQ/view', 'drive:1wT6sgcirZD8va3ZXAiTQrE5uKqwNsEfQ'),
  ('تكيف النباتات في أوساطها', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1iOUGF_Nkwj-D1JhK-wPCdUtTjGLBZplA/view', 'drive:1iOUGF_Nkwj-D1JhK-wPCdUtTjGLBZplA'),
  ('مظاهر تكيف الكائنات الحية مع اوساطها', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1gY1d7AZZEAlZLqQMV5fDjNY6x7I9tMlh/view', 'drive:1gY1d7AZZEAlZLqQMV5fDjNY6x7I9tMlh'),
  ('م21 المميزات العامة للافقاريات', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1Vu_3vS-LwJw4mx8S_6O69Fs-C9c7TobW/view', 'drive:1Vu_3vS-LwJw4mx8S_6O69Fs-C9c7TobW'),
  ('مميزات التكاثر الجنسي عند البناتات الزهرية', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1F2bReN294-9tniVwSzQ6t3n2NbqLQMc0/view', 'drive:1F2bReN294-9tniVwSzQ6t3n2NbqLQMc0'),
  ('الدعامة التشريحية للتكاثر عند النباتات الزهرية', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1R9Al2OQELf0QXjjhzs9UcufZxLIyZmXf/view', 'drive:1R9Al2OQELf0QXjjhzs9UcufZxLIyZmXf'),
  ('التكاثر الخضري عند النبات', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1z8bUP9HcdaZfgSBcstvJHM1Jy8XzrQ5U/view', 'drive:1z8bUP9HcdaZfgSBcstvJHM1Jy8XzrQ5U'),
  ('تركيب الزهرة', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1Sc7OFwjh5NdJQZsLnhJH0oGiP4eVprzM/view', 'drive:1Sc7OFwjh5NdJQZsLnhJH0oGiP4eVprzM'),
  ('م08 تطور نشاط الكائنات الحية عبر الفصول', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1sTq93NxhgkIx_pDbPiF14xUy6B3MXlGZ/view', 'drive:1sTq93NxhgkIx_pDbPiF14xUy6B3MXlGZ'),
  ('م06 تأثير العوامل اللاحيوية على توزع الكائنات الحية ونشاطها', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1sAjvv5V4q8fdjJDwwEYRXSOdqGawkA7-/view', 'drive:1sAjvv5V4q8fdjJDwwEYRXSOdqGawkA7-'),
  ('عرض شهرة', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1MSccSIQ9efB4LsHjiW_zCID-Bie2D6wL/view', 'drive:1MSccSIQ9efB4LsHjiW_zCID-Bie2D6wL'),
  ('تأثير العوامل الفيزيوكيميائية', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/159yPpXfOT-M6r_rvM4LobrzQep95euzz/view', 'drive:159yPpXfOT-M6r_rvM4LobrzQep95euzz'),
  ('العلاقات بين العناصر الحية للوسط الحي', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1R11ER861LQfu32T_zg7N2IqoKY6cFRy-/view', 'drive:1R11ER861LQfu32T_zg7N2IqoKY6cFRy-'),
  ('العلاقات القائمة بين الكائنات الحية', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1nI519LsppSNW_m0Q4mVkxBwtNEWf-8nv/view', 'drive:1nI519LsppSNW_m0Q4mVkxBwtNEWf-8nv'),
  ('2العلاقات القائمة بين العناصر الحية', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1LrEXNKmkNUOicJXTy4sEE_6zbtcVccim/view', 'drive:1LrEXNKmkNUOicJXTy4sEE_6zbtcVccim'),
  ('م02 العلاقات بين الكائنات الحية', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1ra_kq03XjDNRbWB4Q-Nc1LWFzg5nrUR5/view', 'drive:1ra_kq03XjDNRbWB4Q-Nc1LWFzg5nrUR5'),
  ('9', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/119NUKl3DoprberXgTGIxkoewIaLE2Z0_/view', 'drive:119NUKl3DoprberXgTGIxkoewIaLE2Z0_'),
  ('8', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1n3kvxYtAr4Td8oNofkyVnKkMivnRuFSZ/view', 'drive:1n3kvxYtAr4Td8oNofkyVnKkMivnRuFSZ'),
  ('7', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1GlVo6LDpD-ncB3eMnMd_Z2LOgaX0lIZ8/view', 'drive:1GlVo6LDpD-ncB3eMnMd_Z2LOgaX0lIZ8'),
  ('6', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1yEPexxjig3FCxdRTFiZfYFKYV9JMlaqN/view', 'drive:1yEPexxjig3FCxdRTFiZfYFKYV9JMlaqN'),
  ('5', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1mheJ0jQUsZDJRH674uvvBw7puHCkoPyF/view', 'drive:1mheJ0jQUsZDJRH674uvvBw7puHCkoPyF'),
  ('4', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1WQj50pCx-alYFHS3iptbZndD45fz5UhT/view', 'drive:1WQj50pCx-alYFHS3iptbZndD45fz5UhT'),
  ('2', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1jiczDHYgEdPhLOy_eJu2tZ4bqtONv8Li/view', 'drive:1jiczDHYgEdPhLOy_eJu2tZ4bqtONv8Li'),
  ('12', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1tOdSWmEUPFoZ-lHCWJpPdKqdCnrP72rh/view', 'drive:1tOdSWmEUPFoZ-lHCWJpPdKqdCnrP72rh'),
  ('11', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1xVAz3rIJMJdgusDb9RSxUmqApHe_YZbL/view', 'drive:1xVAz3rIJMJdgusDb9RSxUmqApHe_YZbL'),
  ('10', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/10MhuwlB-GUAsEvt3H6qZZzjHtk3dWZdR/view', 'drive:10MhuwlB-GUAsEvt3H6qZZzjHtk3dWZdR'),
  ('1', 'عروض', '2م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1b82vrY-8X0SgpjVsOzotEXBoAH94R7gj/view', 'drive:1b82vrY-8X0SgpjVsOzotEXBoAH94R7gj'),
  ('الخلية', 'عروض', '1م', 'عرض بوربوينت', 'https://drive.google.com/file/d/167oCIR13MhwXtu3uGfo3PCPYXIH_waP_/view', 'drive:167oCIR13MhwXtu3uGfo3PCPYXIH_waP_'),
  ('التخمر', 'عروض', '1م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1Lp1vUHovS_qdr2YvfdYAOhFZoWT6TBQm/view', 'drive:1Lp1vUHovS_qdr2YvfdYAOhFZoWT6TBQm'),
  ('معنى التنفس', 'عروض', '1م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1JwIt3d3bNcF1WC7geth1WzP6Q6ZX3epK/view', 'drive:1JwIt3d3bNcF1WC7geth1WzP6Q6ZX3epK'),
  ('مصدر و تركيب الاغذية', 'عروض', '1م', 'عرض بوربوينت', 'https://drive.google.com/file/d/174-I4XF1s3Ze6bi0Ta4oUYzpXLv9h7qIDDZF6EeaMeU/view', 'drive:174-I4XF1s3Ze6bi0Ta4oUYzpXLv9h7qIDDZF6EeaMeU'),
  ('تركيب الأغذية', 'عروض', '1م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1bUBKuUDdSqkjblHGgC2cs3bFqlttjvVQVe4kCqoGkLc/view', 'drive:1bUBKuUDdSqkjblHGgC2cs3bFqlttjvVQVe4kCqoGkLc'),
  ('المقطع التعلميى 01 س1', 'عروض', '1م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1_6r3TK-5mYuByE-e5_Mpc5pBTRGf8v32/view', 'drive:1_6r3TK-5mYuByE-e5_Mpc5pBTRGf8v32'),
  ('الوضعية الإنطلاقية للمقطع الأول التغذية عند الإنسان', 'عروض', '1م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1h2YXe4Zcy6XiXEApcRe1WBH8Mj1lDsma/view', 'drive:1h2YXe4Zcy6XiXEApcRe1WBH8Mj1lDsma'),
  ('ضرورة العناصر الأساسية للنبات', 'عروض', '1م', 'عرض بوربوينت', 'https://drive.google.com/file/d/17fUSSB1QmW2IzNRY0NO0TkUljzKwqM-B/view', 'drive:17fUSSB1QmW2IzNRY0NO0TkUljzKwqM-B'),
  ('المبادلات الغازية اليخضورية', 'عروض', '1م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1BfkoM5os3FPqx18nIHMa6lhgFQEmmSXl/view', 'drive:1BfkoM5os3FPqx18nIHMa6lhgFQEmmSXl'),
  ('التركيب الضوئي', 'عروض', '1م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1Ln39ygau0Zj7RK72b_BOuW-dac2WKagW/view', 'drive:1Ln39ygau0Zj7RK72b_BOuW-dac2WKagW'),
  ('شروط نمو النبات وتركيب المحلول المعدني', 'عروض', '1م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1WBX8zcWzP7KbKj5y4FXTpq8kf81QHcdf/view', 'drive:1WBX8zcWzP7KbKj5y4FXTpq8kf81QHcdf'),
  ('استعمال المغذيات: لكحل جيلالي', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1HyqWce1OLxgjLCETCo6igNmCa9C5R4Rc/view', 'drive:1HyqWce1OLxgjLCETCo6igNmCa9C5R4Rc'),
  ('المورد-4-الذات-و-اللاذات', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1TPO7k_WvlSsZ0Xv_zXb6K2EKsGOSo1OD/view', 'drive:1TPO7k_WvlSsZ0Xv_zXb6K2EKsGOSo1OD'),
  ('المورد-3-م2ا', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1Gv_eoZ7iejhgSJ6J4lyhBzO7-nUOlKgL/view', 'drive:1Gv_eoZ7iejhgSJ6J4lyhBzO7-nUOlKgL'),
  ('المورد-3 ـ المناعة النوعية', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1NrLxwuaqjWNIDSfZx_yDJayl65IlyVz7/view', 'drive:1NrLxwuaqjWNIDSfZx_yDJayl65IlyVz7'),
  ('المورد-2-م-2ا', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1MU3M_7C_nzMJeZ1GlPymgJKCIvxcIbm7/view', 'drive:1MU3M_7C_nzMJeZ1GlPymgJKCIvxcIbm7'),
  ('المورد-2-المناعة اللانوعية', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1LJZJkN9ge_We7HvKVaTJ7XOOXNpUj7Hx/view', 'drive:1LJZJkN9ge_We7HvKVaTJ7XOOXNpUj7Hx'),
  ('المورد-1ـالحواجز-الطبيعية-و-الاجسام-الغريبة-ـ-المقطع-ت-2_ب_', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1El8ocH37nIo58J6WDqtQ8tl0TLiy0OMf/view', 'drive:1El8ocH37nIo58J6WDqtQ8tl0TLiy0OMf'),
  ('المقطع-ت-2-أ-ـ-المورد1-ـ-النشاط-3', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1xc9XzobUUU2N4cYhcKj2CRI4I8U8Id4a/view', 'drive:1xc9XzobUUU2N4cYhcKj2CRI4I8U8Id4a'),
  ('المقطع-ت-2-أ-ـ-المورد1-ـ-النشاط-2', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/18kr0uEkTzW63bGyWx6W_va5G7hky31h5/view', 'drive:18kr0uEkTzW63bGyWx6W_va5G7hky31h5'),
  ('المقطع-ت-2-أ-ـ-المورد1-ـ-النشاط-1', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1jgPmmKvXbXBiJHUN-S4gBgYrldoT_W2f/view', 'drive:1jgPmmKvXbXBiJHUN-S4gBgYrldoT_W2f'),
  ('الذات و اللاذات', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/189e7Lf1V5FSApixwcI2G49Ub7U4K11iZ/view', 'drive:189e7Lf1V5FSApixwcI2G49Ub7U4K11iZ'),
  ('التنسيق الوظيفي', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1uPq4-ZyJpwA8R4NGxgHNYzKKOJrPPIdR/view', 'drive:1uPq4-ZyJpwA8R4NGxgHNYzKKOJrPPIdR'),
  ('الاعتلالات المناعية', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1NQZY58sfmqsvYfXezNKir88PEDnF0GSk/view', 'drive:1NQZY58sfmqsvYfXezNKir88PEDnF0GSk'),
  ('الاستجابة المناعية', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1btQpdMy3_dvKipaSccp6QeWMUhZ0rO_M/view', 'drive:1btQpdMy3_dvKipaSccp6QeWMUhZ0rO_M'),
  ('الاتصال العصبي', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1Ppdddwh2ejeN5EpXB1G8THev2R3frUba/view', 'drive:1Ppdddwh2ejeN5EpXB1G8THev2R3frUba'),
  ('الاتصال العصبي (2)', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1YH1iDx135HIuFbEsYWJkUKMTWLRSFSn9/view', 'drive:1YH1iDx135HIuFbEsYWJkUKMTWLRSFSn9'),
  ('بلفنطاسي حسين الذات و اللاذات', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1vrJW8XyvHLNDW_UtiKJ_am9zKnUlFagc/view', 'drive:1vrJW8XyvHLNDW_UtiKJ_am9zKnUlFagc'),
  ('المورد5ـ-الاعتلالات-المناعية-', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/16s-gw5SOr98x_er0MdHR0NrK9axmBgW8/view', 'drive:16s-gw5SOr98x_er0MdHR0NrK9axmBgW8'),
  ('المورد-4-ـ-1', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1EfGLOQek-t3-Fb7JY01F-kNeJJ9NPcQ-/view', 'drive:1EfGLOQek-t3-Fb7JY01F-kNeJJ9NPcQ-'),
  ('انتقال الصفات الوراثية', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1GrMglbw9RLaEzLaGfQI0jrtxVwjakFQQ/view', 'drive:1GrMglbw9RLaEzLaGfQI0jrtxVwjakFQQ'),
  ('التوازن الغذائي', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1PD9rxXunzHXy8HqdpCgX-DK93gRUFnGL/view', 'drive:1PD9rxXunzHXy8HqdpCgX-DK93gRUFnGL'),
  ('تحولات الأغذية لكحل جيلالي', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1uH-lEI_odiuo9bw_j_nfYLA5Z8hNkuZu/view', 'drive:1uH-lEI_odiuo9bw_j_nfYLA5Z8hNkuZu'),
  ('تحول الاغذية في الانبوب الهضمي (1)', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1LfwSHvJA70tNpX6-oQOpyh8T4iFd-mv6/view', 'drive:1LfwSHvJA70tNpX6-oQOpyh8T4iFd-mv6'),
  ('مريخي صادقال هضم', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1bk2Ulry7GzdBRp2OkQ5la70wVG4uz0U1/view', 'drive:1bk2Ulry7GzdBRp2OkQ5la70wVG4uz0U1'),
  ('بسمة الربيع مع باور تحولات الاغذية في الانبوب الهضمي', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/11T8vCvoMGQssvE9XKBxWnzYLQEluWkEB/view', 'drive:11T8vCvoMGQssvE9XKBxWnzYLQEluWkEB'),
  ('باور بونت جديد للاستاذة بسمة الربيع مع مورد تحولات الاغذية', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1pqT3knsLaYIvM5xOmQH2jt-RfukcAOOZ/view', 'drive:1pqT3knsLaYIvM5xOmQH2jt-RfukcAOOZ'),
  ('لكحل جيلالي نقل المغذيات', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1qdlCvqK0oSY0yKbWNcXBFep-jJv5PG80/view', 'drive:1qdlCvqK0oSY0yKbWNcXBFep-jJv5PG80'),
  ('مورد نقل المغذيات للاستاذة بسمة الربيع', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1-j4FsXK_DasLUfpO8paFZD8x0fFeEN4J/view', 'drive:1-j4FsXK_DasLUfpO8paFZD8x0fFeEN4J'),
  ('المورد-3-1 ـ الاستاذ بوسعيد ـ 4 م 1', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1qECsM008oKyU-oVMi7qVHAVHOIOiw_RH/view', 'drive:1qECsM008oKyU-oVMi7qVHAVHOIOiw_RH'),
  ('بقاق يوسف التبرع بالدّم', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1n3QKoD8y3uRKNpdFkqMgr3i79iS_MzLY/view', 'drive:1n3QKoD8y3uRKNpdFkqMgr3i79iS_MzLY'),
  ('المورد-5-ـ-التوازن-الغذائي-ـ-4-م-_1', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1Zqz2etlHB1bL1fP4CXhpNQwD4McmyyxM/view', 'drive:1Zqz2etlHB1bL1fP4CXhpNQwD4McmyyxM'),
  ('1 - عواقب السلوكات الغذائية غير الصحية', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1cYiwRZ1SgMVvlHokml5C-BKEe6NXYlUw/view', 'drive:1cYiwRZ1SgMVvlHokml5C-BKEe6NXYlUw'),
  ('لكحل جيلالي الامتصاص المعوي', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1Iesr2nXSZQxSEHsxjuvHQZVV8Kbc1J6o/view', 'drive:1Iesr2nXSZQxSEHsxjuvHQZVV8Kbc1J6o'),
  ('المورد2-الامتصاص-المعوي', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1FtPXm67Z6Juz1IYjdRgKEzz0kJs1D_iC/view', 'drive:1FtPXm67Z6Juz1IYjdRgKEzz0kJs1D_iC'),
  ('المورد2ـ1-ـ-الاستاذ-بوسعيد-4م', 'عروض', '4م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1GHMPNCfC_hkIyhMPYLURW87HtwLwn4cH/view', 'drive:1GHMPNCfC_hkIyhMPYLURW87HtwLwn4cH'),
  ('الاجراءات الوقائية و التنبئية بالبراكين و الزلازل للاستاذ نعيم بوليلة', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1UBggVep4iRNfQgjO5Wsf6F1WNtEwJ0Sm/view', 'drive:1UBggVep4iRNfQgjO5Wsf6F1WNtEwJ0Sm'),
  ('الإجراءات الوقائیة و التنبئیة المتعلقة بالظواھر الجیولوجیة', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1Svn97N_50ikAPuNdidvdPx8t5RGcF5Yy/view', 'drive:1Svn97N_50ikAPuNdidvdPx8t5RGcF5Yy'),
  ('تكتونية-البحر-الأبيض-المتوسط-', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1DK9g6rKhGf8bDQh77PbcYFztt9EG94GqK_pogD06siE/view', 'drive:1DK9g6rKhGf8bDQh77PbcYFztt9EG94GqK_pogD06siE'),
  ('التكتونية في حوض ب ا م', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1umpu5b9YfG3S4-5o-Blq7bk3Nf3SrEJx3xZqf3GIdwY/view', 'drive:1umpu5b9YfG3S4-5o-Blq7bk3Nf3SrEJx3xZqf3GIdwY'),
  ('التكتونية في المتوسط', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1J5jt3GE1bysYcBspxM8KvKwDVhDnti-jc0YvPm2wxhI/view', 'drive:1J5jt3GE1bysYcBspxM8KvKwDVhDnti-jc0YvPm2wxhI'),
  ('تكتونية-البحر-الأبيض-المتوسط-', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/18RbKKYjlEamxJmElgWHrVDP6g7e3N3uK/view', 'drive:18RbKKYjlEamxJmElgWHrVDP6g7e3N3uK'),
  ('التكتونية في حوض ب ا م', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1koGF-bv-8jkfDqjymWR7pRfdir0lMV7_/view', 'drive:1koGF-bv-8jkfDqjymWR7pRfdir0lMV7_'),
  ('التكتونية في حوض البحر الأبيض المتوسط', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1bq8rvVCBtePsy6ikyeAG5-mD42B2GFKd/view', 'drive:1bq8rvVCBtePsy6ikyeAG5-mD42B2GFKd'),
  ('التكتونية في المتوسط', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1iiPudwz2Km3WOuJHjxVSPj2AaW9M5nem/view', 'drive:1iiPudwz2Km3WOuJHjxVSPj2AaW9M5nem'),
  ('النشاط01 أدمج الآليات التفسيرية لأهم الظواهر الجيولوجية', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1A6VbdKfJMt8rWeI-cadzkkuZeqtX6fCPApHS-pyUk3o/view', 'drive:1A6VbdKfJMt8rWeI-cadzkkuZeqtX6fCPApHS-pyUk3o'),
  ('التكتونية العامة والبنية الداخلية للكرة الارضية-1', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1BWPEzbwcxxbJlrM_lHrR00oD8iu-dEUtfotLQAOGWqE/view', 'drive:1BWPEzbwcxxbJlrM_lHrR00oD8iu-dEUtfotLQAOGWqE'),
  ('المورد 05 التكتونية العامة والبنية الداخلية للكرة الأرضية (2)', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1sSpFnNsK8Md7LcZ9yxz4DU5fvoZqLGSw/view', 'drive:1sSpFnNsK8Md7LcZ9yxz4DU5fvoZqLGSw'),
  ('بنية داخلية للكرة', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1P-e3qm65fQdDa8itjOePDDqPwpwYSq0V/view', 'drive:1P-e3qm65fQdDa8itjOePDDqPwpwYSq0V'),
  ('التكتونية العامة والبنية الداخلية للكرة الارضية-1', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1QU-OrqrM0xKrf5AvnoU1Ql2vUj3Xa41Z/view', 'drive:1QU-OrqrM0xKrf5AvnoU1Ql2vUj3Xa41Z'),
  ('النشاط01 أدمج الآليات التفسيرية لأهم الظواهر الجيولوجية', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1IfvGo2brB4zs0SxUnw6a6pADtXOWTwPM/view', 'drive:1IfvGo2brB4zs0SxUnw6a6pADtXOWTwPM'),
  ('عرض المورد الرابع للمقطع الاول', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1RkBWaPtZV1I8GIH8yCMAtu45-kM4ehPnod_wz86Vsmc/view', 'drive:1RkBWaPtZV1I8GIH8yCMAtu45-kM4ehPnod_wz86Vsmc'),
  ('الغوص والظواهر الجيولوجية المرتبطة به', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1TqK2-A1QY-T6zFPv1tTkmKnOMaaBKtjqa6EK0vDWttI/view', 'drive:1TqK2-A1QY-T6zFPv1tTkmKnOMaaBKtjqa6EK0vDWttI'),
  ('مورد الغوص', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1yJpcXCfw6vgW_MVH91KigFyLUDNdYobLg06GCJd12hM/view', 'drive:1yJpcXCfw6vgW_MVH91KigFyLUDNdYobLg06GCJd12hM'),
  ('الغوص والظواهر الجيولوجية المرتبطة به (1)', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1Xt63d5p6vDB6A-kZ_0EhyJR7-N3_CZESQ7k-AoOd3c0/view', 'drive:1Xt63d5p6vDB6A-kZ_0EhyJR7-N3_CZESQ7k-AoOd3c0'),
  ('الغوص والظواهر المرتبطة به (2)', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1DMINsNzkWvuo3ymbIjroVNY4YMjj3Z9eX2nTec3KhAM/view', 'drive:1DMINsNzkWvuo3ymbIjroVNY4YMjj3Z9eX2nTec3KhAM'),
  ('الغوص و الظواهر الجيولوجية المرتبطة به', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/10F2DYfhr69VzMauHpd9GkfqYDJ_1nSn4EgOYPtu4n90/view', 'drive:10F2DYfhr69VzMauHpd9GkfqYDJ_1nSn4EgOYPtu4n90'),
  ('الغوص والظواهر الجيولوجية المرتبطة به (1)', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1xhVgkOZnIYMWAeQAvAmQ-zYq-HQCFlQU/view', 'drive:1xhVgkOZnIYMWAeQAvAmQ-zYq-HQCFlQU'),
  ('الغوص والظواهر المرتبطة به (2)', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1srD80Z1Jq6huayhho5rtG8pbQpLg9FNJ/view', 'drive:1srD80Z1Jq6huayhho5rtG8pbQpLg9FNJ'),
  ('مورد الغوص', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1tpPXhMR_d6U0kEQWbFZWM07awfhWIVY0/view', 'drive:1tpPXhMR_d6U0kEQWbFZWM07awfhWIVY0'),
  ('الغوص والظواهر الجيولوجية المرتبطة به.', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1rNK667UXA9ykfkl49B_u5-S3XZHW5Cm7/view', 'drive:1rNK667UXA9ykfkl49B_u5-S3XZHW5Cm7'),
  ('الغوص والظواهر المرتبطة به', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1zRNPrv1gGxT0pFtK1gvcm1cIL5xNtWmY/view', 'drive:1zRNPrv1gGxT0pFtK1gvcm1cIL5xNtWmY'),
  ('الغوص و الظواهر الجيولوجية المرتبطة به', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1Wy6ktuE7My3CoDuPnBoSe8NAliQKvZU6/view', 'drive:1Wy6ktuE7My3CoDuPnBoSe8NAliQKvZU6'),
  ('الغوص والظواهر الجيولوجية المرتبطة به', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1JLCB5H3-PwOWMtQ-gJCVfGpRY64aFv_A/view', 'drive:1JLCB5H3-PwOWMtQ-gJCVfGpRY64aFv_A'),
  ('عرض المورد الرابع للمقطع الاول', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/13jnjedg4m-7LLprt_tJG1vBitDOkCyBV/view', 'drive:13jnjedg4m-7LLprt_tJG1vBitDOkCyBV'),
  ('الغوص والظواهر الجيولوجية المرتبطة به', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1CsgUISQoXrG1JtxK34Ob8_3rAZasP2Kr/view', 'drive:1CsgUISQoXrG1JtxK34Ob8_3rAZasP2Kr'),
  ('مورد نشاط الظهرات', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1U81cK3UrxcQ_ZCOwmP5g0CpmlLOu_hj8LZCHcVRkUCY/view', 'drive:1U81cK3UrxcQ_ZCOwmP5g0CpmlLOu_hj8LZCHcVRkUCY'),
  ('Copie de نشاط الظهرات', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1Xc1Ax9FFzzF47qfRc2a4Mg1SkPwnU7hMlA0k_VocScc/view', 'drive:1Xc1Ax9FFzzF47qfRc2a4Mg1SkPwnU7hMlA0k_VocScc'),
  ('زحزحة القارات ونشاط الظهرات', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1e3NnOxPgS3k9kWL-Es7jfywlto60jGBe/view', 'drive:1e3NnOxPgS3k9kWL-Es7jfywlto60jGBe'),
  ('نشاط الظهرات (1)', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1ZutnP7DjVyRLFFH5_OcLKWB3cEyXW4lb/view', 'drive:1ZutnP7DjVyRLFFH5_OcLKWB3cEyXW4lb'),
  ('daharate diapo', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1duxUTQ5ULUh9Pxc_KmKq3Cw8M9u4sN8u/view', 'drive:1duxUTQ5ULUh9Pxc_KmKq3Cw8M9u4sN8u'),
  ('مورد نشاط الظهرات', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1A9VsnlxPHweewSvrZeaRmtyDhjotEjgW/view', 'drive:1A9VsnlxPHweewSvrZeaRmtyDhjotEjgW'),
  ('النشاط 3 أفسر زحزحة القارات بنشاط الظهرات', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/16TU4WCcc2HpZiX5ny6MAqXjlgkog-b_z/view', 'drive:16TU4WCcc2HpZiX5ny6MAqXjlgkog-b_z'),
  ('نشاط الظهرات', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1BqOyxJa5iv1deUPRqA8tLrTzK9qqgp5c/view', 'drive:1BqOyxJa5iv1deUPRqA8tLrTzK9qqgp5c'),
  ('أسباب الزلازل', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/16sALQfDivMaaw8KvLGuyMF4konGo_EyG55Zb5KxNw6E/view', 'drive:16sALQfDivMaaw8KvLGuyMF4konGo_EyG55Zb5KxNw6E'),
  ('أسباب الزلازل', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1kc8UawaX39Idndna7y_nAPs8kvCJQYAt/view', 'drive:1kc8UawaX39Idndna7y_nAPs8kvCJQYAt'),
  ('أسباب الزلازل (1)', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1oxNHo9aW0A4Y86opcikP-c9q7M8Eozz-/view', 'drive:1oxNHo9aW0A4Y86opcikP-c9q7M8Eozz-'),
  ('ا الزلازل ظاهرة طبيعية', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1GviIZh4yrnDPToBiZNPK2VbVvHJs2LW90WtGe0GXxDU/view', 'drive:1GviIZh4yrnDPToBiZNPK2VbVvHJs2LW90WtGe0GXxDU'),
  ('الزلازل ظاهرة طبيعية', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1jz7m9-1eeUgdlkbI9mLx63cUfE2uyzVSuDvrYEaltLw/view', 'drive:1jz7m9-1eeUgdlkbI9mLx63cUfE2uyzVSuDvrYEaltLw'),
  ('ا الزلازل ظاهرة طبيعية', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1WPoFouMU2lcv7mHkDVKtUhodnNTbXpmP/view', 'drive:1WPoFouMU2lcv7mHkDVKtUhodnNTbXpmP'),
  ('الزلازل ظاهرة طبيعية', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1zzIaV2OzG35SxvXy9dxqekq5BlBHz2nJ/view', 'drive:1zzIaV2OzG35SxvXy9dxqekq5BlBHz2nJ'),
  ('بسمة الربيع مع الديناميكية الداخلية للكرة الارضية', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1MBwNFBJ6vLoU7eBzZRy6NFRCYisckdwc/view', 'drive:1MBwNFBJ6vLoU7eBzZRy6NFRCYisckdwc'),
  ('asbab-zelzal', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1leTesHvfYbGgYG19sv2k8JDu57SkJvsz/view', 'drive:1leTesHvfYbGgYG19sv2k8JDu57SkJvsz'),
  ('تقويم المورد1الزلازل ظاهرة طبيعية', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1GFxBw3ttPL_HIx3VlnrsEtUHfsR-9XFR/view', 'drive:1GFxBw3ttPL_HIx3VlnrsEtUHfsR-9XFR'),
  ('فرضية مصدر الزلازل', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1NzRWc3Y6I__KtvPeEJznxOvBl3cIhmRU/view', 'drive:1NzRWc3Y6I__KtvPeEJznxOvBl3cIhmRU'),
  ('1 - 5البؤرة وانتشار الأمواج الزلزالیة', 'عروض', '3م', 'عرض بوربوينت', 'https://drive.google.com/file/d/1WNJqLS_dO1e8gI4g10cVDNWa-EzuArjT/view', 'drive:1WNJqLS_dO1e8gI4g10cVDNWa-EzuArjT');
