-- ==============================================================================
-- 🌟 كود إعداد قاعدة بيانات Supabase الشامل لمنصة SAC · SVT prof 🌟
-- انسخ هذا الكود كاملاً والصقه في: Supabase → SQL Editor → New query → اضغط Run
-- ==============================================================================

-- 1️⃣ جدول المستخدمين والمسؤولين (users) ---------------------------------------
CREATE TABLE IF NOT EXISTS public.users (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name              TEXT,
  email             TEXT UNIQUE NOT NULL,
  password          TEXT NOT NULL,
  type              TEXT NOT NULL DEFAULT 'user',   -- 'user' | 'admin'
  subscription_days INTEGER DEFAULT 30,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at        TIMESTAMPTZ
);

-- دالة حساب تاريخ انتهاء صلاحية اشتراك المستخدم تلقائياً
CREATE OR REPLACE FUNCTION public.set_user_expiry()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.type = 'admin' THEN
    NEW.expires_at := NULL;                       -- المسؤول بلا تاريخ انتهاء (صلاحية دائمة)
  ELSIF NEW.subscription_days IS NOT NULL THEN
    NEW.expires_at := now() + (NEW.subscription_days || ' days')::interval;
  END IF;
  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS trg_user_expiry ON public.users;
CREATE TRIGGER trg_user_expiry
  BEFORE INSERT OR UPDATE OF subscription_days, type ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.set_user_expiry();

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "users_all" ON public.users;
CREATE POLICY "users_all" ON public.users FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- إضافة حساب المسؤول الرئيسي (الأدمين) تلقائياً
INSERT INTO public.users (name, email, password, type, subscription_days)
VALUES ('قريمس أماني (الأدمين)', 'grimesamani98@gmail.com', 'admin123', 'admin', NULL)
ON CONFLICT (email) DO NOTHING;

INSERT INTO public.users (name, email, password, type, subscription_days)
VALUES ('مسؤول المنصة', 'admin@sac-svt.dz', 'admin123', 'admin', NULL)
ON CONFLICT (email) DO NOTHING;


-- 2️⃣ جدول الملفات والمذكرات المرفوعة (files) -----------------------------------
CREATE TABLE IF NOT EXISTS public.files (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       TEXT NOT NULL,
  category    TEXT,                 -- مذكرات / وثائق / عروض / فروض / كتب
  level       TEXT,                 -- 1م / 2م / 3م / 4م / عام
  description TEXT,
  url         TEXT NOT NULL,        -- الرابط العام للملف
  path        TEXT,                 -- مسار الملف داخل الحاوية السحابية
  uploaded_by TEXT,                 -- اسم أو بريد الأستاذ الرافِع
  file_ext    TEXT,                 -- امتداد الملف (pdf, docx, pptx)
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS files_created_at_idx ON public.files (created_at DESC);
ALTER TABLE public.files ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "read_files_public" ON public.files;
CREATE POLICY "read_files_public" ON public.files FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "insert_files_public" ON public.files;
CREATE POLICY "insert_files_public" ON public.files FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "delete_files_public" ON public.files;
CREATE POLICY "delete_files_public" ON public.files FOR DELETE TO anon, authenticated USING (true);


-- 3️⃣ حاوية التخزين السحابي للملفات (files bucket) ------------------------------
INSERT INTO storage.buckets (id, name, public)
VALUES ('files', 'files', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "storage_read_files" ON storage.objects;
CREATE POLICY "storage_read_files" ON storage.objects FOR SELECT TO anon, authenticated USING (bucket_id = 'files');

DROP POLICY IF EXISTS "storage_insert_files" ON storage.objects;
CREATE POLICY "storage_insert_files" ON storage.objects FOR INSERT TO anon, authenticated WITH CHECK (bucket_id = 'files');

DROP POLICY IF EXISTS "storage_delete_files" ON storage.objects;
CREATE POLICY "storage_delete_files" ON storage.objects FOR DELETE TO anon, authenticated USING (bucket_id = 'files');


-- 4️⃣ جدول التعليقات والمناقشات (comments) --------------------------------------
CREATE TABLE IF NOT EXISTS public.comments (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,          -- اسم صاحب التعليق
  comment     TEXT NOT NULL,          -- نص التعليق
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS comments_created_at_idx ON public.comments (created_at DESC);
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "read_comments_public" ON public.comments;
CREATE POLICY "read_comments_public" ON public.comments FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "insert_comments_public" ON public.comments;
CREATE POLICY "insert_comments_public" ON public.comments FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "delete_comments_public" ON public.comments;
CREATE POLICY "delete_comments_public" ON public.comments FOR DELETE TO anon, authenticated USING (true);

-- ==============================================================================
-- ✅ انتهى الإعداد الشامل بنجاح! جميع الجداول والحاويات جاهزة الآن لخدمة منصتك.
-- ==============================================================================
