-- ============================================================
--  إعداد قاعدة بيانات منصة SAC · SVT prof
--  الصق هذا الكود كاملاً في: Supabase → SQL Editor → New query → Run
-- ============================================================

-- 1) جدول الملفّات ---------------------------------------------------------
create table if not exists public.files (
  id          bigint generated by default as identity primary key,
  title       text not null,
  category    text,                 -- مذكرات / وثائق / عروض / فروض / كتب
  level       text,                 -- 1م / 2م / 3م / 4م / عام
  description text,
  url         text not null,        -- الرابط العام للملف
  path        text,                 -- مسار الملف داخل الحاوية (للحذف لاحقًا)
  created_at  timestamptz not null default now()
);

-- فهرس لتسريع الترتيب حسب الأحدث
create index if not exists files_created_at_idx on public.files (created_at desc);

-- 2) تفعيل الحماية على مستوى الصفوف (RLS) ---------------------------------
alter table public.files enable row level security;

-- السماح للجميع بقراءة قائمة الملفّات (المكتبة عامة)
drop policy if exists "read_files_public" on public.files;
create policy "read_files_public"
  on public.files for select
  to anon, authenticated
  using (true);

-- السماح بالإضافة (الرفع) — عام لأن اللوحة محمية بكلمة مرور من التطبيق
drop policy if exists "insert_files_public" on public.files;
create policy "insert_files_public"
  on public.files for insert
  to anon, authenticated
  with check (true);

-- السماح بالحذف (لإدارة الملفات لاحقًا)
drop policy if exists "delete_files_public" on public.files;
create policy "delete_files_public"
  on public.files for delete
  to anon, authenticated
  using (true);

-- 3) حاوية التخزين (bucket) عامة باسم files -------------------------------
insert into storage.buckets (id, name, public)
values ('files', 'files', true)
on conflict (id) do update set public = true;

-- 4) سياسات التخزين -------------------------------------------------------
-- قراءة عامة لكل الملفّات داخل الحاوية
drop policy if exists "storage_read_files" on storage.objects;
create policy "storage_read_files"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'files');

-- السماح برفع الملفّات إلى الحاوية
drop policy if exists "storage_insert_files" on storage.objects;
create policy "storage_insert_files"
  on storage.objects for insert
  to anon, authenticated
  with check (bucket_id = 'files');

-- السماح بحذف الملفّات من الحاوية
drop policy if exists "storage_delete_files" on storage.objects;
create policy "storage_delete_files"
  on storage.objects for delete
  to anon, authenticated
  using (bucket_id = 'files');

-- ============================================================
--  انتهى ✅  — بعد التشغيل الناجح: اذهب إلى Settings → API
--  وانسخ:  Project URL  +  anon public key
--  ثم أدخلهما في «لوحة الإدارة ← الإعدادات» داخل التطبيق.
-- ============================================================
